ChatManager2024-AB-master/Controllers/ChatRoomController.cs
using ChatManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace ChatManager.Controllers
{
    public class ChatRoomController : Controller
    {
        // GET: ChatRoom
        [OnlineUsers.UserAccess]
        public ActionResult Index()
        {
            Session["LastAction"] = "/ChatRoom/Index";
            Session["SelecId"] = 0;
            return View();
        }
        public ActionResult Conv(bool forceRefresh = false)
        {
            if (forceRefresh || OnlineUsers.HasChanged() || DB.Friendships.HasChanged || DB.Messages.HasChanged )
            {
                var loggedUser = OnlineUsers.GetSessionUser();
                //user Sélectionné
                User userSelec;
                if ((int)Session["SelecId"] == 0)
                    userSelec = null;
                else
                    userSelec = DB.Users.Get((int)Session["SelecId"]);
                //liste messages
                IEnumerable<IEnumerable<Models.Message>> listMessages;
                if (userSelec == null)
                    listMessages = null;
                else
                    listMessages = DB.Messages.GetConv(OnlineUsers.GetSessionUser().Id, (int)Session["SelecId"]);

                //liste d'amis
                List<User> filteredUsers = new List<User>(); 
                List<User> users =
                    DB.Users.SortedUsers().ToList().Where(u => u.Verified).ToList();
                foreach (User user in users)
                {
                    if (DB.Friendships.RelationStatus(loggedUser.Id, user.Id) == EnumRelationStatus.Friend)
                    {
                        filteredUsers.Add(user);
                    }

                }
                //Vérif si une amitié a changé
                if(userSelec != null && !DB.Friendships.AreFriends(OnlineUsers.GetSessionUser().Id, (int)Session["SelecId"]))
                {
                    userSelec = null;
                    listMessages = null;
                    Session["SelecId"] = 0;
                }
                (IEnumerable<User> amis, User user,IEnumerable<IEnumerable<Models.Message>> messages) retour = (filteredUsers, userSelec, listMessages);
                return PartialView(retour);
            }

            return null;
        }

        public void SendMessage(string message, bool forceRefresh = false)
        {
            if((int)Session["SelecID"] != 0 && Session["SelecID"] != null)
            {
                var objMessage = new Models.Message(OnlineUsers.GetSessionUser().Id, (int)Session["SelecID"]);
                objMessage.content = message;
                DB.Messages.Add(objMessage);
            }
        }
        public void SetSelec(int usrID)
        {
            Session["SelecId"] = usrID;
        }
        public void UpdateMessage(int messageID, string message)
        {
            var messageInit = DB.Messages.Get(messageID);
            if(messageInit != null && messageInit.usrSource == OnlineUsers.GetSessionUser().Id)
            {
                messageInit.content = message;
                DB.Messages.Update(messageInit);
            }
        }
        public void DeleteMessage(int messageID)
        {
            var messageInit = DB.Messages.Get(messageID);
            if (messageInit != null && messageInit.usrSource == OnlineUsers.GetSessionUser().Id)
            {
                DB.Messages.Delete(messageID);
            }
        }
        [OnlineUsers.AdminAccess]
        public ActionResult Admin()
        {
            return View();
        }
        public ActionResult AdminMessages(bool forceRefresh = false)
        {
            if (forceRefresh || OnlineUsers.HasChanged()  || DB.Messages.HasChanged)
            {
                var listeMessage = DB.Messages.ToList().OrderByDescending(m => m.Id).ToList();
                return PartialView(listeMessage);
            }
            return null;
        }
    }
}

ChatManager2024-AB-master/Views/ChatRoom/Admin.cshtml
<h2>Conversations</h2>
<hr />
<div class="convAdminContainer" id="convAdminContainer">

</div>
@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
<script>
        $(function () {
            let adminList = new PartialRefresh("@Url.Action("AdminMessages","ChatRoom")", "convAdminContainer", 5, Update);
            function Update()
            {
                $('.deleteMessage').click(
                    function () {
                        let id = $(this).attr('id').split('_')[1];
                        friendsList.confirmedCommand("Voulez vous vraiment supprimer le message ?","@Url.Action("DeleteMessage", "ChatRoom")" + "?messageId=" + id)
                    }
                )
            }

        })
</script>
}

ChatManager2024-AB-master/Views/ChatRoom/AdminMessages.cshtml
@model IEnumerable<ChatManager.Models.Message>
@if (Model != null)
{
    foreach (var message in Model)
    {
        <div class="messageCell">
            @Helper.Image(ChatManager.Models.DB.Users.Get(message.usrSource).Avatar, "UserAvatarChatRoom")
            @Helper.Image(ChatManager.Models.DB.Users.Get(message.usrTarget).Avatar, "UserAvatarChatRoom")
            @if (!ChatManager.Models.DB.Users.Get(message.usrSource).IsAdmin || ChatManager.Models.OnlineUsers.GetSessionUser().Id == message.usrSource)
            {
                @Helper.Icon("supprimmerAdmin_" + message.Id, "fa-times-circle fa-3 deleteMessage", "Supprimmer le Message")
            }
            else
            {
                <div class="icon"></div>
            }
            <div class="sentMessage" title="Envoyé le @message.Date.ToString("dd MMMM yyy à HH:mm")">
                <span>@Helper.ParseContent(@message.content)</span>
            </div>

        </div>
    }
}

ChatManager2024-AB-master/Views/ChatRoom/Conv.cshtml
@model (IEnumerable<ChatManager.Models.User> amis, ChatManager.Models.User user, IEnumerable<IEnumerable<ChatManager.Models.Message>> messages)
<div class="friendsContainer" id="friendsContainer">
    @foreach (var friend in Model.amis)
    {
        if (Model.user != null && friend.Id == Model.user.Id)
        {
            <div class="userImgContainer" id="Usr_@friend.Id" title="@friend.GetFullName()" style="border: solid green 4px">
                @Helper.Image(friend.Avatar, "UserAvatarChatRoom")
            </div>
        }
        else
        {
            <div class="userImgContainer" id="Usr_@friend.Id" title="@friend.GetFullName()">
                @Helper.Image(friend.Avatar, "UserAvatarChatRoom")
            </div>
        }
    }
</div>
<div class="messagesSectionContainer">
    <div class="messagesInBox" id="messagesInBox">
        @if (Model.user != null)
        {
            <div class="titleContainer">
                <span>Conversation avec</span>
                <div class="titleUserContainer">
                    @Helper.Image(Model.user.Avatar, "UserAvatarChatRoom")
                    <span>@Model.user.GetFullName()</span>
                </div>
            </div>
            <div id="convContainer" class="convContainer">
                @if (Model.messages.ElementAt(0).Count() != 0)
                {
                    foreach (var dateMessage in Model.messages)
                    {
                        <div class="messageDate">
                            <span>@dateMessage.ElementAt(0).Date.ToString("dd MMMM yyy - HH:mm")</span>
                        </div>
                        foreach (var message in dateMessage)
                        {
                            if (message.usrSource == Model.user.Id)
                            {
                                <div class="receivedMessage" title="Reçu le @message.Date.ToString("dd MMMM yyy à HH:mm")"><span>@message.content</span></div>
                            }
                            else
                            {
                                <div class="messageContainer" id="message_@message.Id">
                                    <div class="sentMessage" title="Envoyé le @message.Date.ToString("dd MMMM yyy à HH:mm")">
                                        <span>@Helper.ParseContent(@message.content)</span>
                                        <div class="modifier">
                                            <input class="input_modifier" type="text" value="@message.content" />
                                        </div>
                                    </div>
                                    @Helper.Icon("modifier", "fa-check fa-3 updateMessage", "Envoyer le Message")
                                    @Helper.Icon("supprimmer", "fa-times fa-3 deleteMessage", "Envoyer le Message")
                                </div>
                            }
                        }
                    }
                }

                <div id="last"></div>
            </div>
            <div class="messagesContainer"></div>
        }
        else
        {
            <div class="titleContainer">
                <span>Aucune Conversation Sélectionnée</span>
            </div>
            <div class="messagesContainer"></div>
        }
    </div>
</div>
<script>
    //propriété scroll -> https://openclassrooms.com/forum/sujet/faire-scroller-un-chat-automatiquement-vers-le-bas
    var messages = document.getElementById("last");
        if(messages !== null) 
            messages.scrollIntoView();
    $('.sentMessage').click(
        function () {
            $('.modifier').hide();
            $('.updateMessage').hide();
            $('.deleteMessage').hide();
            $('.sentMessage > span').show();
            $('.sentMessage').removeClass("sentMessageModifier");
            $('.input_modifier').val($(this).find('span').text())
            $(this).find("span").hide();
            $(this).find(".modifier").show();
            $(this).addClass("sentMessageModifier");
            $(this).parent().find('#modifier').show();
            $(this).parent().find('#supprimmer').show();


        }
    )

</script>

ChatManager2024-AB-master/Views/ChatRoom/Index.cshtml
@{
    ViewBag.TitleUpSection = "ChatRoom";
}


<h2>@Helper.ImageCmd("ChatRoom", "Admin", "/Content/UI-Icons/chatRoom.png", "ImgTitle", "")Salle de clavardage</h2>
<hr />
<div class="chatRoomContainer">
    <div class="UpSection" id="UpSection">

        @*<div class="friendsContainer" id="friendsContainer">

            </div>*@
        @*<div class="messagesSectionContainer">
                <div class="messagesInBox" id="messagesInBox">
                    <div class="titleContainer">
                        <span>Aucune Conversation Sélectionnée</span>
                    </div>
                    <div class="messagesContainer"></div>
                </div>
                <div class="sendContainer">
                    <input class="sendInput" type="text" placeholder="Tapez votre message içi ..." />
                    @Helper.Icon("sendIcon", "fa-paper-plane fa-3 sendIcon", "Envoyer le Message")
                </div>
            </div>*@
    </div>
    <div class="sendContainer">
        <input class="sendInput" type="text" placeholder="Tapez votre message içi ..." />
        @Helper.Icon("sendIcon", "fa-paper-plane fa-3 sendIcon", "Envoyer le Message")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
        $(function ()
        {
            let friendsList = new PartialRefresh("@Url.Action("Conv","ChatRoom")", "UpSection", 5, Update);
            $('.sendIcon').click(
                function () {
                    if ($('.sendInput').val().trim() != null && $('.sendInput').val().trim() != "")
                        friendsList.command("@Url.Action("SendMessage", "ChatRoom")" + "?message=" + $('.sendInput').val().trim());

                    $('.sendInput').val('');
                }
            )
            //https://api.jquery.com/keydown/
            $('.sendInput').on('keydown',
                function (event) {
                    if (event.keyCode === 13) {
                        if ($('.sendInput').val().trim() != null || $('.sendInput').val().trim() != "") { }
                        friendsList.command("@Url.Action("SendMessage", "ChatRoom")" + "?message=" + $('.sendInput').val().trim());
                        $('.sendInput').val('');
                    }
                    else if (event.keyCode === 27) {
                        $('.sendInput').val('');
                    }
                }
            )
            function Update() {
                $('.userImgContainer').click(
                    function () {
                        console.log(this.id.split('_')[1]);
                        let id = this.id.split('_')[1];
                        friendsList.command("@Url.Action("SetSelec", "ChatRoom")" + "?usrId=" + id);
                    }
                );
                $('.updateMessage').click(
                    function () {
                        let id = $(this).parent().attr('id').split('_')[1];
                        let value = $(this).parent().find('.sentMessage').find('.modifier').find('.input_modifier').val().trim();
                        friendsList.command("@Url.Action("UpdateMessage", "ChatRoom")" + "?messageId=" + id + "&message=" + value)
                    }
                );
                $('.input_modifier').on('keydown',
                    function (event) {
                        if (event.keyCode === 13) {
                            let id = $(this).parent().parent().parent().attr('id').split('_')[1];
                            let value = $(this).val().trim();
                            friendsList.command("@Url.Action("UpdateMessage", "ChatRoom")" + "?messageId=" + id + "&message=" + value)
                        }
                        else if (event.keyCode === 27) {
                            $('.modifier').hide();
                            $('.updateMessage').hide();
                            $('.deleteMessage').hide();
                            $('.sentMessage > span').show();
                            $('.sentMessage').removeClass("sentMessageModifier");
                        }
                    }
                );
                $('.deleteMessage').click(
                    function () {
                        let id = $(this).parent().attr('id').split('_')[1];
                        friendsList.confirmedCommand("Voulez vous vraiment supprimer le message ?","@Url.Action("DeleteMessage", "ChatRoom")" + "?messageId=" + id)
                    }
                )
            }
    })

</script>
}